FROM python:3.11.3-slim-bullseye

COPY ./ /app/

RUN python3 -m pip install -r /app/requirements.txt

RUN python3 /app/manage.py migrate

ENV PRODUCTION false
ENV PRODUCTION_ARGUMENT ""

CMD sh /app/run.sh