FROM python:3.11.4-bullseye

WORKDIR /app
COPY ./ /app/

RUN python3 -m pip install -r ./requirements.txt
RUN python3 -m pip install uwsgi

RUN python3 /app/manage.py migrate

ENV PRODUCTION true
ENV PRODUCTION_ARGUMENT "--socket /app/backend.sock"

CMD sh /app/run.sh