# Generated by Django 4.1.7 on 2023-05-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TFLiteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=64, unique=True)),
                ("n_layers", models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="TFLiteFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "tflite_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tflite_files",
                        to="train.tflitemodel",
                    ),
                ),
            ],
        ),
    ]
