# Generated by Django 4.2.1 on 2023-05-17 03:02

import django.db.models.deletion
import train.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        encoder=train.models.NumpyEncoder,
                    ),
                ),
                (
                    "tflite_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="train.tflitemodel",
                    ),
                ),
            ],
        ),
    ]
