# Generated by Django 4.2.1 on 2023-06-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0002_modelparams"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="modelparams",
            name="tflite_model",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="params",
                to="train.tflitemodel",
            ),
        ),
        migrations.AlterField(
            model_name="tflitefile",
            name="tflite_model",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tflite_files",
                to="train.tflitemodel",
            ),
        ),
        migrations.AddField(
            model_name="tflitemodel",
            name="data_type",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tflite_models",
                to="train.trainingdatatype",
            ),
            preserve_default=False,
        ),
    ]
