# Generated by Django 4.2.1 on 2023-06-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitInsTelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(editable=False, max_length=100)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fit_ins",
                        to="telemetry.trainingsession",
                    ),
                ),
            ],
        ),
    ]
