# Generated by Django 4.2.1 on 2023-06-09 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0002_modelparams"),
        ("telemetry", "0002_fitinstelemetrydata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitinstelemetrydata",
            name="end",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="fitinstelemetrydata",
            name="session_id",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fit_ins",
                to="telemetry.trainingsession",
            ),
        ),
        migrations.AlterField(
            model_name="fitinstelemetrydata",
            name="start",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="tflite_model",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_sessions",
                to="train.tflitemodel",
            ),
        ),
        migrations.CreateModel(
            name="EvaluateInsTelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField(editable=False)),
                ("start", models.DateTimeField(editable=False)),
                ("end", models.DateTimeField(editable=False)),
                ("loss", models.FloatField(editable=False)),
                ("accuracy", models.FloatField(editable=False)),
                ("test_size", models.IntegerField(editable=False)),
                (
                    "session_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluate_ins",
                        to="telemetry.trainingsession",
                    ),
                ),
            ],
        ),
    ]
