on:
  push:
    paths: '**.py'
jobs:
  Black:
    name: Check Black format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
