on:
  push:
    paths:
      - '.github/workflows/flutter-android.yml'
      - '**.dart'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: |
          cd fed_kit_client/
          flutter pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Test
        run: flutter test
      - uses: actions/setup-java@v2
      - name: Build APK
        run: |
          flutter build apk
          flutter build appbundle
